//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CV_201211264.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_CV_201211264TYPE            130
#define ID_IMAGELOAD_BMPLOAD            32771
#define ID_IMAGELOAD_JPEGLOAD           32772
#define ID_PROCESSING_OTUSMETHOD        32773
#define ID_PROCESSING_OTSUMETHOD        32774
#define ID_PROCESSING_DILATION          32775
#define ID_PROCESSING_EROSION           32776
#define ID_PROCESSING_MORDILATION       32777
#define ID_PROCESSING_MORDILATION32778  32778
#define ID_PROCESSING_MOREROSION        32779
#define ID_PROCESSING_OPENING           32780
#define ID_PROCESSING_CLOSING           32781
#define ID_PROCESSING_CUSTERMIZED       32782
#define ID_PROCESSING_MORDILATIONWITHSPECIALCASE 32783
#define ID_PROCESSING_MOREROSIONWITHSPECIALCASE 32784
#define ID_LABELING_ROW                 32785
#define ID_LABELING_RUN                 32786
#define ID_LABELING_LABELINGWITHAREA    32787
#define ID_LABELING_LABELINGWITHCENTROID 32788
#define ID_LABELING_LABELINGWITHBOUNDINGBOX 32789
#define ID_LABELING_LABELINGWITHCIRCULARITY 32790
#define ID_LABELING_LABELINGWITHORIENTATION 32791
#define ID_EXTRACTFEATURE_EXTRACT       32792
#define ID_NEAREST_NEIGHBOR             32793
#define ID_NEAREST_MEAN                 32794
#define ID_NEURALNETWORK_NE             32795
#define ID_CLUSTERING_KMEANS            32796
#define ID_CLUSTERING_AGGLOMERATIVE     32797
#define ID_NEURALNETWORK                32798
#define ID_NEURALNETWORK_TESTING        32799
#define ID_CLUSTERING_TESTING           32800

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        310
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
